fix retries escape and data network for backups

diff --git a/authentik/docker-compose.yml b/authentik/docker-compose.yml
--- a/authentik/docker-compose.yml
+++ b/authentik/docker-compose.yml
@@ -6,12 +6,12 @@ services:
     command: |
       sh -c "
         RETRIES=30
-        until pg_isready -h ${POSTGRES_HOST} -U ${POSTGRES_SUPER_USER} || [ \$RETRIES -eq 0 ]; do
-          echo \"Waiting for PostgreSQL... (\$RETRIES retries left)\";
-          RETRIES=\$((RETRIES-1))
+        until pg_isready -h ${POSTGRES_HOST} -U ${POSTGRES_SUPER_USER} || [ $$RETRIES -eq 0 ]; do
+          echo \"Waiting for PostgreSQL... ($$RETRIES retries left)\";
+          RETRIES=$$((RETRIES-1))
           sleep 2;
         done;
-        [ \$RETRIES -eq 0 ] && echo 'Postgres not ready, aborting' && exit 1;
+        [ $$RETRIES -eq 0 ] && echo 'Postgres not ready, aborting' && exit 1;
         psql postgresql://${POSTGRES_SUPER_USER}:${POSTGRES_SUPER_PASSWORD}@${POSTGRES_HOST}:5432/postgres <<-EOSQL
           SELECT 'CREATE USER ${POSTGRES_AUTHENTIK_USER} WITH PASSWORD ''${POSTGRES_AUTHENTIK_PASSWORD}'''
           WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = '${POSTGRES_AUTHENTIK_USER}')\gexec
